#server:
#  port: 8080
#  servlet:
#    context-path: /
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 12519712132-7vumu8kl5dg47gllei1dtuf4rdoa975j.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile

          facebook:
            client-id: 448518554351919
            client-secret: 383d3ca41bbf309f67607b3ca59316fb
            scope:
            - email
            - public_profile

          naver:
            client-id: Gqs1P8o_hhlp76S20bYa
            client-secret: dUfYJT5UCs
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: http://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌