spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/boardservice
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace

jwt:
  secret: 79085a5938b3394054690b28923023cc573db5b623c862c1cfdf0e20036a96d3